baseURL = "https://umerjamil16.github.io/"
title = "Umer Jamil "
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-3GF17TX34N"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Umer Jamil"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Umer Jamil"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Umer Jamil"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = """
It’s a work in progress. Here is what I do know about me, but please let me know if you know more

I am a cyclist and pedal around 10 km daily.
I love solo traveling, hiking, and mountain trekking (unless I am joined by someone intellectual and we can discuss some of the most complex ideas of life).
I keep a journal.
I am an avid book reader. Genres included: Autobiography, Biography, Memoirs, Encyclopedia, Psychology, Science, and Technology

Currently, I am working as a Cloud DevOps engineer working at the Rayn Group. My primary work is in the area of DevOps, Mobile DevOps, DevSecOps, AWS Cloud and MLOps. My focus is on Cloud Native technologies and building SaaS platforms.
Moreover, I’ve expertise in the following areas:

DevOps and MLOps
Automatic Speech Recognition (ASR) and Computer Vision
Robotics: Kinematics, Motion Planning, Path Planning, Manipulation, Localisation, Perception 

I hold a BE in Mechatroncis and MS in Robotics and AI from NUST, Pakistan.


  """

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/umerjamil_"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/umerjamil/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/umerjamil16"


[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "#"
  Text = "Suggest Changes (Disabled)"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20



[markup.highlight]
noClasses = false

